server:
  port: 10002
spring:
  application:
    name: file
  cloud:
    nacos:
      server-addr: localhost:8848
  datasource:
    username: root
    password: lsk123456
    url: jdbc:mysql://localhost:3306/netdisk_file
    driver-class-name: com.mysql.cj.jdbc.Driver