spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
  datasource:
    username: root
    password: lsk123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/netdisk_gateway